flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required             
from flaskblog.models import Post              
from flaskblog.posts.forms import PostForm     
from flaskblog import db                                        


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('your post has been created !', 'success')

        return redirect(url_for('main.home'))

    return render_template('pages/create_post.html', title='New Post', 
                            form=form, legend='New Post')



@posts.route("/post/<int:post_id>")  #or "/post/<post_id>"
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('pages/post.html', title=post.title, post=post)


#you cant have the same function name for multiple routes... 

@posts.route("/post/<int:post_id>/update", methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():           #if the update form was being sent... 
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()                 #since you are just updating something that is in the database... 
        flash('Your post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':       #populate the form with those values... 
        form.title.data = post.title
        form.content.data = post.content

    return render_template('pages/create_post.html', title='Update Post', 
                            form=form, legend='Update Form')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)     #delete post.. 
    db.session.commit()

    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint            
from flaskblog.models import User, Post
from flask_login import login_user, logout_user, current_user, login_required  
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog.users.forms import myLoginForm, myRegForm, myUpdateAccount, RequestResetForm, ResetPasswordForm      
from flaskblog import db, bcrypt                                                         


users = Blueprint('users', __name__)


#Render Forms....
@users.route("/register", methods=['GET','POST'])
def register():

    if current_user.is_authenticated:                   # if user is already l
        return redirect (url_for('main.home'))

    form = myRegForm()
    if form.validate_on_submit():
       
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') # #first string instead of bytes        
        user = User(username=form.username.data, email=form.email.data, password=hashed_password) #add user to database.
        db.session.add(user)
        db.session.commit();

        #flash them a message..
        flash('Your Account has been created! you can now login..', 'success')  #f-toinclude variables..
        return redirect(url_for('users.login'))        # redirect to name of route..

    return render_template('pages/register.html', title='Register', form=form)



@users.route("/login", methods=['GET','POST'])   #handle login forms...
def login():
    
    if current_user.is_authenticated:                   # if user is already logged-in, redirect to home..
        return redirect (url_for('main.home'))

    form = myLoginForm()
    if form.validate_on_submit():

        #check if user exist... 
        user = User.query.filter_by(email=form.username.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('main.home'))   # tenary operator in python...
        else:    
            flash('login unsuccessful, pls check usrname and password', 'danger')    
  
    return render_template('pages/login.html', title='Login', form=form)  #then render-template if error in form submission.....

    

'''if form.username.data == 'admin@blog.com' and form.password.data == 'password':
    flash('you have been logged in!', 'success')
    return redirect(url_for('main.home'))
else:'''



@users.route("/logout")
def logout():
    logout_user();
    return redirect(url_for('main.home'))





@users.route("/account",  methods=['GET','POST'])
@login_required
def account():
    form = myUpdateAccount()

    if form.validate_on_submit():
        if form.picture.data:                            # check if it has a picture file..
            current_user.image_file = save_picture(form.picture.data)       # pass the new name to the current user object...

        current_user.username = form.username.data;
        current_user.email = form.email.data

        db.session.commit();
        flash('your account has been updated', 'success')
        return redirect(url_for('users.account'))             #...to avoid a post/get/redirect error... 

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data    = current_user.email

    imgfile = url_for('static', filename='uploads/' + current_user.image_file)
    return render_template('pages/account.html', title='AccountPage', profile_pix=imgfile, form=form)




@users.route("/user/<string:username>")                                          #  include another route...
def user_posts(username):
    
    page = request.args.get('page', 1, type=int)                            #   page, default page, type=integer...    
    user = User.query.filter_by(username=username).first_or_404()    
                                                                            #   backslash to go to a new line ~ no Spaces... 
    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=2)           #.all()  #order by date..

    return render_template('pages/user_posts.html', posts=posts, user=user)    





@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:                   # so they are logged out before they change their password..
       return redirect (url_for('main.home'))
      
    form = RequestResetForm() 
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.username.data).first()       # first user with that email..
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('pages/reset_request.html', title='Reset Password', form=form)  




@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:                  
       return redirect (url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None: 
       flash('that is an invalid or expired token', 'warning')
       return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():           
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') # #first string instead of bytes        
        user.password = hashed_password
        db.session.commit();

        #flash them a message..
        flash('Your password has been updated..', 'success')  #f-toinclude variables..
        return redirect(url_for('users.login'))        # redirect to name of route..


    return render_template('pages/reset_token.html', title='Reset Password', form=form)  

flaskblog/templates/pages/about.html
{% extends 'layout.html' %}

{% block body %}

<h1>About Page</h1>

{% endblock body %}

flaskblog/templates/pages/account.html
{% extends 'layout.html' %}

{% block body %}

<h1>Account Page</h1>

    <div class="content-section">
        <div class="media">
            <img src="{{profile_pix}}" alt="" class="rounded-circle account-img"/>
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <!-- FORM HERE -->


        <form method="POST" action="" enctype="multipart/form-data"> 
            {{ form.hidden_tag() }}  <!-- adds the csrf token.. -->
            <fieldset class="form-group">
                

                <div class="form-group">
                    {{form.username.label(class="form-control-label")}}
                    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.username(class="form-control form-control-lg")}}
                    {% endif %}                        
                </div>

                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class="form-control form-control-lg")}}
                    {% endif %}
                </div>

                <div class="form-group">
                    
                    {{form.picture.label()}}
                    {{form.picture(class="from-control-file")}}

                    {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                        <span class="text-danger">{{error}}</span>
                      {% endfor %}
                    {% endif %}
                </div>
                
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
        
        
        


    </div>

<hr>
<br/>
<br/>
<small>
    Welcome to the {{ current_user.username }} account's page... 
    if user is not logged in it redirects to login_manager.login_view page 
    using the @login_required decorator... #noted
</small>

{% endblock body %}

flaskblog/templates/pages/create_post.html
{% extends 'layout.html' %}

{% block body %}

 
<div class="content-section">
    <form method="POST" action=""> 
        {{ form.hidden_tag() }}  <!-- adds the csrf token.. -->
        <fieldset class="form-group">
            <legend class="mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.title(class="form-control form-control-lg")}}
                {% endif %}
  
            </div>

            
            <div class="form-group">
                {{form.content.label(class="form-control-label")}}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.content(class="form-control form-control-lg")}}
                {% endif %}
            </div>

        </fieldset>



        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
        
    </form>
</div>


{% endblock body %}

flaskblog/templates/pages/home.html
{% extends 'layout.html' %}

{% block body %}

<h1>Home Page</h1>

    {% for post in posts.items%}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row"> 
              <div class="col-sm-6">
                    <h6 class="m-0 font-weight-bold text-primary">                      
                      <img class="img-profile rounded-circle" height="32" width="32" src="{{url_for('static', filename='uploads/'+post.author.image_file)}}"> &nbsp;
                      <a href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a>
                    </h6>
              </div>
              <div class="col-sm-5">
                <a class="mr-2 text-muted" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d, %h:%m') }}</small>
              </div>
          </div>
        </div>
        <div class="card-body"> {{post.content[0:90]}}... </div>
        <small class="text-muted" style="font-size:9px;display:block;color:#e6e6e6 !important;padding:4px 10px;">
            {{post.key}}
        </small>
    </div>


    {% endfor%}


   
    {%  for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)  %}

      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{url_for('main.home', page=page_num)}}"> {{page_num}}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{url_for('main.home', page=page_num)}}"> {{page_num}}</a>
        {% endif %}  
      {% else %}
        .....
      {% endif %}

    {%  endfor %}


{% endblock %}

flaskblog/templates/pages/login.html
{% extends 'layout.html' %}

{% block body %}

<div class="content-section">
    <form method="POST" action=""> 
        {{ form.hidden_tag() }}  <!-- adds the csrf token.. -->
        <fieldset class="form-group">
            <legend class="mb-4">Log In</legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.username(class="form-control form-control-lg")}}
                {% endif %}

                
            </div>

            
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.password(class="form-control form-control-lg")}}
                {% endif %}
            </div>

            <div class="form-check"> 
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>

        </fieldset>



        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>

<div class="border-top pt-3">
    <small class="text-muted">
        <a class="ml-2" href="{{ url_for('users.reset_request') }}"> forgot password ?</a>
    </small>
    <br/>
    <small class="text-muted">
        i dont have an account, <a class="ml-2" href="{{url_for('users.register')}}"> Sign Up here</a>
    </small>
</div>

{% endblock body %}

flaskblog/templates/pages/post.html
{% extends 'layout.html' %}

{% block body %}

<h1>Home Page</h1>



    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row"> 
              <div class="col-sm-6">
                    <h6 class="m-0 font-weight-bold text-primary">                      
                      <img class="img-profile rounded-circle" height="32" width="32" src="{{url_for('static', filename='uploads/'+post.author.image_file)}}"> &nbsp;
                      {{post.title}}

                      {% if post.author == current_user %} 
                        <a class="btn" href="{{url_for('posts.update_post', post_id=post.id) }}">update</a> / <a class="btn" data-toggle="modal" data-target="#deleteModal" href="">delete</a>
                      {% endif %}
                    </h6>
              </div>
              <div class="col-sm-5">
                <a class="mr-2 text-muted" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d, %h:%m') }}</small>
              </div>
          </div>
        </div>
        <div class="card-body"> {{post.content}} </div>
        <small class="text-muted" style="font-size:9px;display:block;color:#e6e6e6 !important;padding:4px 10px;">
            {{post.key}}
        </small>
    </div>

    <!----- Example Modal... ----->

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post ? </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <!-- <div class="modal-body"></div> -->
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

              <form action="{{ url_for('posts.delete_post', post_id=post.id)}}" method="POST"><Input type="submit" class="btn btn-danger" value="Delete"/></form>

            </div>
          </div>
        </div>
      </div>


   

{% endblock %}

flaskblog/templates/pages/register.html
{% extends 'layout.html' %}

{% block body %}

<div class="content-section">
    <form method="POST" action=""> 
        {{ form.hidden_tag() }}  <!-- adds the csrf token.. -->
        <fieldset class="form-group">
            <legend class="mb-4">Join Today</legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.username(class="form-control form-control-lg")}}
                {% endif %}

                
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.password(class="form-control form-control-lg")}}
                {% endif %}
            </div>
            <div class="form-group">
                {{form.confirm_password.label(class="form-control-label")}}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.confirm_password(class="form-control form-control-lg")}}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>

<div class="border-top pt-3">
    <small class="text-muted">
        Already has an account ?  <a class="ml-2" href="{{url_for('users.login')}}">Sign In</a>
    </small>
</div>

{% endblock body %}

flaskblog/templates/pages/reset_request.html
{% extends 'layout.html' %}

{% block body %}

<div class="content-section">
    <form method="POST" action=""> 
        {{ form.hidden_tag() }}  <!-- adds the csrf token.. -->
        <fieldset class="form-group">
            <legend class="mb-4">Reset Password</legend>
            
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.username(class="form-control form-control-lg")}}
                {% endif %}
                
            </div>

        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
    
</div>

{% endblock body %}

flaskblog/templates/pages/reset_token.html
{% extends 'layout.html' %}

{% block body %}

<div class="content-section">
    <form method="POST" action=""> 
        {{ form.hidden_tag() }}  <!-- adds the csrf token.. -->
        <fieldset class="form-group">
            <legend class="mb-4">Reset Password</legend>
            
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.passwordconfirm_.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.password(class="form-control form-control-lg")}}
                {% endif %}
                
            </div>

            <div class="form-group">
                {{form.confirm_password.label(class="form-control-label")}}
                
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.confirm_password(class="form-control form-control-lg")}}
                {% endif %}
                
            </div>


        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
    
</div>

{% endblock body %}

flaskblog/templates/pages/user_posts.html
{% extends 'layout.html' %}

{% block body %}

<h1 class="mb-3"> Posts by {{user.username}} ({{posts.total}}) </h1>

    {% for post in posts.items%}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row"> 
              <div class="col-sm-6">
                    <h6 class="m-0 font-weight-bold text-primary">                      
                      <img class="img-profile rounded-circle" height="32" width="32" src="{{url_for('static', filename='uploads/'+post.author.image_file)}}"> &nbsp;
                      <a href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a>
                    </h6>
              </div>
              <div class="col-sm-5">
                <a class="mr-2 text-muted" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d, %h:%m') }}</small>
              </div>
          </div>
        </div>
        <div class="card-body"> {{post.content}} </div>
        <small class="text-muted" style="font-size:9px;display:block;color:#e6e6e6 !important;padding:4px 10px;">
            {{post.key}}
        </small>
    </div>


    {% endfor%}


   
    {%  for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)  %}

      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}"> {{page_num}}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}"> {{page_num}}</a>
        {% endif %}  
      {% else %}
        .....
      {% endif %}


    {%  endfor %}


{% endblock %}