flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post                                      


main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")                                                                               # include another route...
def home():
    page = request.args.get('page', 1, type=int)                                                   # page, default page, type=integer...
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)           # all()  #order by date..
    return render_template('pages/home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('pages/about.html', title='About')

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required             
from flaskblog.models import Post              
from flaskblog.posts.forms import PostForm     
from flaskblog import db                                        


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('your post has been created !', 'success')

        return redirect(url_for('main.home'))

    return render_template('pages/create_post.html', title='New Post', 
                            form=form, legend='New Post')



@posts.route("/post/<int:post_id>")  #or "/post/<post_id>"
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('pages/post.html', title=post.title, post=post)


#you cant have the same function name for multiple routes... 

@posts.route("/post/<int:post_id>/update", methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():           #if the update form was being sent... 
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()                 #since you are just updating something that is in the database... 
        flash('Your post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':       #populate the form with those values... 
        form.title.data = post.title
        form.content.data = post.content

    return render_template('pages/create_post.html', title='Update Post', 
                            form=form, legend='Update Form')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)     #delete post.. 
    db.session.commit()

    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint            
from flaskblog.models import User, Post
from flask_login import login_user, logout_user, current_user, login_required  
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog.users.forms import myLoginForm, myRegForm, myUpdateAccount, RequestResetForm, ResetPasswordForm      
from flaskblog import db, bcrypt                                                         


users = Blueprint('users', __name__)


#Render Forms....
@users.route("/register", methods=['GET','POST'])
def register():

    if current_user.is_authenticated:                   # if user is already l
        return redirect (url_for('main.home'))

    form = myRegForm()
    if form.validate_on_submit():
       
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') # #first string instead of bytes        
        user = User(username=form.username.data, email=form.email.data, password=hashed_password) #add user to database.
        db.session.add(user)
        db.session.commit();

        #flash them a message..
        flash('Your Account has been created! you can now login..', 'success')  #f-toinclude variables..
        return redirect(url_for('users.login'))        # redirect to name of route..

    return render_template('pages/register.html', title='Register', form=form)



@users.route("/login", methods=['GET','POST'])   #handle login forms...
def login():
    
    if current_user.is_authenticated:                   # if user is already logged-in, redirect to home..
        return redirect (url_for('main.home'))

    form = myLoginForm()
    if form.validate_on_submit():

        #check if user exist... 
        user = User.query.filter_by(email=form.username.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('main.home'))   # tenary operator in python...
        else:    
            flash('login unsuccessful, pls check usrname and password', 'danger')    
  
    return render_template('pages/login.html', title='Login', form=form)  #then render-template if error in form submission.....

    

'''if form.username.data == 'admin@blog.com' and form.password.data == 'password':
    flash('you have been logged in!', 'success')
    return redirect(url_for('main.home'))
else:'''



@users.route("/logout")
def logout():
    logout_user();
    return redirect(url_for('main.home'))





@users.route("/account",  methods=['GET','POST'])
@login_required
def account():
    form = myUpdateAccount()

    if form.validate_on_submit():
        if form.picture.data:                            # check if it has a picture file..
            current_user.image_file = save_picture(form.picture.data)       # pass the new name to the current user object...

        current_user.username = form.username.data;
        current_user.email = form.email.data

        db.session.commit();
        flash('your account has been updated', 'success')
        return redirect(url_for('users.account'))             #...to avoid a post/get/redirect error... 

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data    = current_user.email

    imgfile = url_for('static', filename='uploads/' + current_user.image_file)
    return render_template('pages/account.html', title='AccountPage', profile_pix=imgfile, form=form)




@users.route("/user/<string:username>")                                          #  include another route...
def user_posts(username):
    
    page = request.args.get('page', 1, type=int)                            #   page, default page, type=integer...    
    user = User.query.filter_by(username=username).first_or_404()    
                                                                            #   backslash to go to a new line ~ no Spaces... 
    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=2)           #.all()  #order by date..

    return render_template('pages/user_posts.html', posts=posts, user=user)    





@users.route("/reset_password", methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:                   # so they are logged out before they change their password..
       return redirect (url_for('main.home'))
      
    form = RequestResetForm() 
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.username.data).first()       # first user with that email..
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('pages/reset_request.html', title='Reset Password', form=form)  




@users.route("/reset_password/<token>", methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:                  
       return redirect (url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None: 
       flash('that is an invalid or expired token', 'warning')
       return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():           
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') # #first string instead of bytes        
        user.password = hashed_password
        db.session.commit();

        #flash them a message..
        flash('Your password has been updated..', 'success')  #f-toinclude variables..
        return redirect(url_for('users.login'))        # redirect to name of route..


    return render_template('pages/reset_token.html', title='Reset Password', form=form)  

flaskblog/templates/partials/navbar.html
 <!-- Topbar -->
 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
      <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

      <!-- Nav Item - Search Dropdown (Visible Only XS) -->
      <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
          <form class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Nav Item - Alerts -->
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <!-- Counter - Alerts -->
          <span class="badge badge-danger badge-counter">3+</span>
        </a>
        <!-- Dropdown - Alerts -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">
            Alerts Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-primary">
                <i class="fas fa-file-alt text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 12, 2019</div>
              <span class="font-weight-bold">A new monthly report is ready to download!</span>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-success">
                <i class="fas fa-donate text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 7, 2019</div>
              $290.29 has been deposited into your account!
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="mr-3">
              <div class="icon-circle bg-warning">
                <i class="fas fa-exclamation-triangle text-white"></i>
              </div>
            </div>
            <div>
              <div class="small text-gray-500">December 2, 2019</div>
              Spending Alert: We've noticed unusually high spending for your account.
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
        </div>
      </li>

      <!-- Nav Item - Messages -->
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <!-- Counter - Messages -->
          <span class="badge badge-danger badge-counter">7</span>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">
            Message Center
          </h6>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
              <div class="status-indicator bg-success"></div>
            </div>
            <div class="font-weight-bold">
              <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
              <div class="small text-gray-500">Emily Fowler · 58m</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
              <div class="status-indicator"></div>
            </div>
            <div>
              <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
              <div class="small text-gray-500">Jae Chun · 1d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
              <div class="status-indicator bg-warning"></div>
            </div>
            <div>
              <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
              <div class="small text-gray-500">Morgan Alvarez · 2d</div>
            </div>
          </a>
          <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
              <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
              <div class="status-indicator bg-success"></div>
            </div>
            <div>
              <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
              <div class="small text-gray-500">Chicken the Dog · 2w</div>
            </div>
          </a>
          <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
        </div>
      </li>

      <div class="topbar-divider d-none d-sm-block"></div>

      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          
          {% if current_user.is_authenticated %}
          
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ current_user.username }}</span>
          <img class="img-profile rounded-circle" src="{{url_for('static', filename='uploads/' + current_user.image_file)}}">
          
          {% else %}

          <span class="mr-2 d-none d-lg-inline text-gray-600 small">...pls login in</span>
          <img class="img-profile rounded-circle" src="{{url_for('static', filename='uploads/default.jpg')}}">

          {% endif %}

        </a>




        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </div>
      </li>

    </ul>

  </nav>
  <!-- End of Topbar -->

flaskblog/templates/partials/sidebar.html
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">My Blog <sup>X</sup></div>
        </a>
  
        <!-- Divider
        <hr class="sidebar-divider my-0">
        -->


        <!-- Heading -->
        <div class="sidebar-heading">
          Main Menu
        </div>
  
        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('main.home')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Home </span></a>
        </li>
  
        <!-- Divider -->
        <hr class="sidebar-divider">

        

        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.about')}}">
            <i class="fas fa-fw fa-table"></i>
            <span>About</span></a>
        </li>
   
  
        <!-- Divider -->
        <hr class="sidebar-divider">



        {% if current_user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.account')}}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>My Account</span></a>
        </li>
 
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('posts.new_post')}}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>New Post</span></a>
        </li>

        
        <hr class="sidebar-divider">


        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.logout')}}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>LogOUT</span></a>
        </li>

        {% else %}
        
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.login')}}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Login</span></a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.register')}}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Register</span></a>
        </li>  

        {% endif %}


  
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">
  
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
  
      </ul>
      <!-- End of Sidebar -->